apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: auth
type: Opaque
stringData:
  client-id: "filebrowser"
  client-secret: zLNO1RVQ4lgnhjPu1MQQMQHf9Ww9ti+ZqzkfzQYLYi4=
  cookie-secret: hUysVHod8sJaViFR3gTB3w==
