apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-filebrowser
provisioner: smb.csi.k8s.io
parameters:
  source: "//172.31.64.1/k8sdata"
  csi.storage.k8s.io/provisioner-secret-name: smbcreds
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: smbcreds
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0770
  - file_mode=0660
  - uid=1000
  - gid=1000
  - vers=3.0