apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home
    color: slate
    headerStyle: clean
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - datetime:
        text_size: xl
        format:
          dateStyle: short
          timeStyle: short
  services.yaml: |
    - Storage:
        - File Browser:
            href: https://files.home.nipo
            description: SMB-backed file browser
            icon: sh-filebrowser
  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - abbr: GH
              href: https://github.com/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  custom.css: ""
  custom.js: ""
